### ISSUE TITLE
No clean uninstall

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/uh-installer#1]
The folder /python and /unknown-horizons and C:\Users\linux\Documents\My Games\unknown-horizons
dont get uninstalled.

**Comment by LinuxDonald** [comment]
@jakoch maybe you could help here when you find time?

**Comment by jakoch** [comment]
sure. 

that sounds like we need to add an `[UninstallDelete]` section with some custom entries...
http://jrsoftware.org/ishelp/topic_uninstalldeletesection.htm

For the folder `C:\Users\linux\Documents\` we could use the constant `{userdocs}`..
http://jrsoftware.org/ishelp/topic_consts.htm#group

```
[UninstallDelete]
Type: filesandordirs; Name: "{userdocs}\My Games\unknown-horizons"
Type: filesandordirs; Name: "{app}\python"
Type: filesandordirs; Name: "{app}\unknown-horizons"
```

**Comment by LinuxDonald** [comment]
Fixed with: https://github.com/unknown-horizons/uh-installer/commit/dab0ac97aaf9b0209eadcba7a7ad7d0903226a2c

I dont added: Type: filesandordirs; Name: "{userdocs}\My Games\unknown-horizons"
Because maybe users dont want that it get delete.

**Comment by jakoch** [comment]
It might be possible to add `Flags: postinstall nowait skipifsilent unchecked`.
Which should display a "by default unchecked" checkbox, asking the user, if he wants to delete the content.
Not sure, if that works..

**Comment by LinuxDonald** [comment]
Ah thanks I will test that tomorrow :-)
