### ISSUE TITLE
generate_atlases.py fails

### ISSUE THREAD

**Issue by jakoch** [unknown-horizons/uh-installer#3]
https://ci.appveyor.com/project/LinuxDonald/uh-installer/build/2017.1.67#L161

```
cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons"
python horizons\engine\generate_atlases.py 1024
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Recreating all atlases
Traceback (most recent call last):
  File "horizons\engine\generate_atlases.py", line 431, in <module>
    generator.recreate()
  File "horizons\engine\generate_atlases.py", line 272, in recreate
    self.save()
  File "horizons\engine\generate_atlases.py", line 230, in save
    self._save_metadata()
  File "horizons\engine\generate_atlases.py", line 344, in _save_metadata
    with open(PATHS.ATLAS_METADATA_PATH, 'wb') as file:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\appveyor\\Documents\\My Games\\unknown-horizons\\atlas-metadata.cache'
```

**Comment by LinuxDonald** [comment]
On linux i become the same error. Only when i run UH with Atlas support turned on. After one start of uh the script works. I think thats an uh bug and must be fixed there.


my suggestion would be: That we create an branch on uh for release with atlas files in it and use it for the installer. Because i dont think we will become this fixed in python in the next weeks.

**Comment by LinuxDonald** [comment]
I´ve done some testing atlas support is broken on windows.
https://github.com/unknown-horizons/unknown-horizons/issues/2596

**Comment by jakoch** [comment]
In other words: You need to install UH one time, then the files are installed into the user's document folder: `C:\\Users\\appveyor\\Documents\\My Games\\unknown-horizons\\atlas-metadata.cache`.
Only afterwards one is able to run the Atlas generation? 

Yes.. that needs a fix, so that ideally the Atlas generation is done on Appveyor.

**Comment by jakoch** [comment]
The `.gitignore` file might be relevant here, too.
https://github.com/unknown-horizons/unknown-horizons/blob/master/.gitignore
The files/folders in gitignore are removed from the content of the repository, when the zip is build by git.
In regard to the UH-2596 issue: is it possible that files are missing?

**Comment by LinuxDonald** [comment]
Fixed in git.
