### ISSUE TITLE
Unable to find _fife on windows 10 x64

### ISSUE THREAD

**Issue by MasterofJOKers** [unknown-horizons/uh-installer#5]
Using the installer (https://ci.appveyor.com/api/buildjobs/ylqvaba67o3l6djd/artifacts/Unknown-Horizons-2017.1.121-Setup-VC14-x86.exe) UH does not find fife "no module named _fife" on a windows 10 x64.

**Comment by MasterofJOKers** [comment]
Someone left his mail address on IRC to get a notification once this is fixed. I wrote it down somewhere.

**Comment by LinuxDonald** [comment]
[dlls.txt](https://github.com/unknown-horizons/uh-installer/files/735402/dlls.txt)

Here is the list of loaded dlls files that UH/fife needs

**Comment by LinuxDonald** [comment]
Fife and Fifechan DLL need what we no install:
MSVCP140.dll
VCRUNTIME140.dll

**Comment by jakoch** [comment]
When `*140.dll` files are missing, then the target system needs the VCRedist2015 package (x86-VC14).
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by LinuxDonald** [comment]
Should be fixed with: https://github.com/unknown-horizons/unknown-horizons/releases/download/2017.1/Unknown-Horizons-2017.1.128-Setup-VC14-x86.exe

@jakoch fife sdk have now too the dlls because fife and fifechan needs it.

**Comment by jakoch** [comment]
Ok. Let's hope that adding the dlls alone is sufficient. If not, the proper way to install vcredist is to include the vcredist installer and do a check if vcredist needs to be installed and then trigger a silent install.

**Comment by squiddy** [comment]
This seems to be fixed, right? @linuxdonald

**Comment by LinuxDonald** [comment]
Yeah I hope it is fixed.
