### ISSUE TITLE
Exclude unnecessary files

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/uh-installer#8]
I installed the game using the installer and it includes unnecessary files, such as:

Mypy.ini
.editorconfig
...

Right now it seems that some files are deleted explicitly when building the installer. Perhaps it's a good idea to consult the MANIFEST.IN file in the uh repo.

**Comment by squiddy** [comment]
You do realise there are more files and not just literally the ones I mentioned **as an example?** Reopening.

**Comment by jakoch** [comment]
I've updated the stripdown script.
We are down to ~115MB compressed installer filesize and ~235 MB after install.

- [MANIFEST.IN](https://github.com/unknown-horizons/unknown-horizons/blob/master/MANIFEST.in)
- [Stripdown Script](https://github.com/unknown-horizons/uh-installer/blob/master/build-scripts/4-stripdown.bat)

We could try to delete more stuff from the Python folder. It's ~90Mb after install.
For instance `python/DLLs/tcl86t.dll` and similar files. The TCL root folder is already removed.
It would be interesting to drop unnecessary stuff from `python\Lib`?
But i'm not sure, what Python itself needs and what's removable to get to a minimal version.

Feel free to append the stripdown script.
